crab_steering_controller:
  state_joints: {
    type: string_array,
    default_value: [],
    description: "(optional) Specifies joints for reading states. This parameter is only relevant when state joints are different then command joint, i.e., when a following controller is used.",
    read_only: true,
  }
  front_left_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front left drive joints used by the controller.",
    read_only: true,
  }
  front_right_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front right drive joints used by the controller.",
    read_only: true,
  }
  rear_left_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear left drive joints used by the controller.",
    read_only: true,
  }
  rear_right_drive_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear right drive joints used by the controller.",
    read_only: true,
  }
  front_left_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front left swerve joints used by the controller.",
    read_only: true,
  }
  front_right_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the front right swerve joints used by the controller.",
    read_only: true,
  }
  rear_left_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear left swerve joints used by the controller.",
    read_only: true,
  }
  rear_right_swerve_joint: {
    type: string,
    default_value: "",
    description: "Specifies the rear right swerve joints used by the controller.",
    read_only: true,
  }
  wheel_radius: {
    type: double,
    default_value: 0.254,
    description: "Specifies wheel radius calculation purposes. ",
    read_only: true,
  }
