<?xml version="1.0"?>
<package format="3">
  <name>usb_camera_relay</name>
  <version>0.0.0</version>
  <description>Publishes USB camera streams as sensor_msgs/Image ROS topics</description>
  <maintainer email="todo@todo.com">UMD Loop</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
