athena_gps:
  ros__parameters:
    usb_path: "serial:///dev/ttyACM0:57600"

    imu_rate: 10.0
    gps_info_rate: 1.0
    attitude_rate: 10.0

    imu_frame_id: "imu_link"
    gps_frame_id: "gps_link"

    imu_topic: "imu/data"
    gps_topic: "gps/fix"
    heading_topic: "heading"

    mavsdk_system_id: 10
    mavsdk_component_id: 1
    mavsdk_always_send_heartbeats: false
