science_manual:
  state_joints:
    type: string_array
    default_value: []
    description: >
      (optional) Specifies joints for reading states. This parameter is only relevant
      when state joints are different then command joint, i.e., when a following controller is used.
    read_only: true
    validation:
      unique<>: null

  interface_name:
    type: string
    default_value: ""
    description: >
      Name of the interface used by the controller on joints and command_joints.
    read_only: true
    validation:
      not_empty<>: null
      one_of<>: [["position", "velocity", "acceleration", "effort"]]
      forbidden_interface_name_prefix: null

  command_interfaces:
    type: string_array
    default_value: ["velocity", "position"]

  state_interfaces:
    type: string_array
    default_value: ["velocity", "position"]

  pump_right:
    type: string
    default_value: "stepper_motor_a"
    description: "First Stepper Motor"
    read_only: true
    validation:
      not_empty<>: null

  pump_left:
    type: string
    default_value: "stepper_motor_b"
    description: "Second Stepper Motor"
    read_only: true
    validation:
      not_empty<>: null

  scoops_lift_f:
    type: string
    default_value: "servo_scoops_lift_f"
    description: "The Servo motor controller for the left-sided rack and pinion"
    read_only: true
    validation:
      not_empty<>: null

  scoops_lift_b:
    type: string
    default_value: "servo_scoops_lift_b"
    description: "The Servo motor controller for the right-sided rack and pinion"
    read_only: true
    validation:
      not_empty<>: null

  sampler_lift_f:
    type: string
    default_value: "servo_sampler_lift_f"
    description: "(Optional)"
    read_only: false

  sampler_lift_b:
    type: string
    default_value: "servo_sampler_lift_b"
    description: "(Optional)"
    read_only: false

  conveyor_belt:
    type: string
    default_value: "servo_conveyor_belt"
    description: "(Optional)"
    read_only: false
  
  scoop_servos:
    type: string_array
    default_value: ["servo_scoop_f", "servo_scoop_b"]
    description: "The servos for the scoop (2 servos)"
    read_only: true
    validation:
      unique<>: null
      not_empty<>: null

  scoop_spinner:
    type: string
    default_value: "dc_scoop"
    description: "Scoop DC motor"
    read_only: true
    validation:
      not_empty<>: null

  auger_spinner:
    type: string
    default_value: "dc_auger"
    description: "(Optional)"
    read_only: false

  auger_lift:
    type: string
    default_value: "servo_auger_lift"
    description: "The Servo motor controller for the auger lift"
    read_only: true
    validation:
      not_empty<>: null
  
  # Pumps
  velocity_limits_pumps:
    type: double_array
    default_value: [20.0, 0.0, 0.6, 0.0]
    validation:
      fixed_size<>: 4

  # Scoops
  # Scoops Lift
  velocity_limits_scoops_lift:
    type: double_array
    default_value: [200.0, 0.1, 0.0, 0.3]
    validation:
      fixed_size<>: 4

  # Scoops  
  position_range_scoop_servo_f:
    type: double_array
    default_value: [20.0, 120.0]
    validation:
      fixed_size<>: 2

  position_range_scoop_servo_b:
    type: double_array
    default_value: [0.0, 110.0]
    validation:
      fixed_size<>: 2

  # Scoops Spinner
  velocity_limits_scoop_spinner:
    type: double_array
    default_value: [30.0, 0.0, 0.6, 0.0]
    validation:
      fixed_size<>: 4

  # Sampler
  # Sampler Lift
  velocity_limits_sampler_lift:
    type: double_array
    default_value: [200.0, 0.0, 0.0, 0.6]
    validation:
      fixed_size<>: 4

  # Auger
  velocity_limits_auger:
    type: double_array
    default_value: [2.5, 0.0, 0.0, 0.6]
    validation:
      fixed_size<>: 4

  position_range_auger_lift:
    type: double_array
    default_value: [5.0, 360.0]
    validation:
      fixed_size<>: 2

  # Conveyor Belt
  velocity_limits_conveyor_belt:
    type: double_array
    default_value: [200.0, 0.0, 0.0, 0.6]
    validation:
      fixed_size<>: 4
