controller_manager:
  ros__parameters:
    update_rate: 100  # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:             
      type: position_controllers/JointGroupPositionController

    joint_group_velocity_controller:              
      type: velocity_controllers/JointGroupVelocityController

    science_controller:
      type: science_controllers/ScienceManual

    laser_gpio_controller:
      type: gpio_controllers/GpioCommandController

    fluoro_led_gpio_controller:
      type: gpio_controllers/GpioCommandController

    motor_status_controller:
      type: general_controllers/MotorStatusController

joint_group_position_controller:                
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_rack_and_pinion_l
      - servo_rack_and_pinion_r
      - servo_scoop_a
      - servo_scoop_b
      - dc_scoop
      - servo_sampler_lift_l
      - servo_sampler_lift_l
      - dc_auger
      - servo_auger_lift
    interface_name: position

joint_group_velocity_controller:                 
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_rack_and_pinion_l
      - servo_rack_and_pinion_r
      - servo_scoop_a
      - servo_scoop_b
      - dc_scoop
      - servo_sampler_lift_l
      - servo_sampler_lift_r
      - dc_auger
      - servo_auger_lift
    interface_name: velocity

science_controller:
  ros__parameters:
    # Pumps
    pump_a: "stepper_motor_a"
    pump_b: "stepper_motor_b"
    
    # Lift
    lift_rack_and_pinion_l: "servo_rack_and_pinion_l"
    lift_rack_and_pinion_r: "servo_rack_and_pinion_r"
    
    # Scoops
    scoop_servos: ["servo_scoop_a", "servo_scoop_b"]
    scoop_spinner: "dc_scoop"

    # Sampler
    sampler_lift_l: "servo_sampler_lift_l"
    sampler_lift_r: "servo_sampler_lift_r"
    auger_spinner: "dc_auger"
    cap: "servo_auger_lift"
    interface_name: position 
    command_interfaces: [position, velocity]
    state_interfaces: [position, velocity]

# Laser GPIO Controller Configuration
laser_gpio_controller:
  ros__parameters:
    gpios:
      - spectrometry_laser
    command_interfaces:
      spectrometry_laser:
        interfaces:
          - laser_command
    state_interfaces:
      spectrometry_laser:
        interfaces:
          - laser_state
          - temperature
          - is_connected

fluoro_led_gpio_controller:
  ros__parameters:
    gpios:
      - fluoro_led
    command_interfaces:
      fluoro_led:
        interfaces:
          - intensity

# Default command interfaces: 
# - status_request
# - maintenance_request
# - maintenance_frame_high
# - maintenance_frame_low
# - maintenance_data_count

# Default state interfaces:
# - motor_temperature
# - torque_current
# - status
motor_status_controller:
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_rack_and_pinion_l
      - servo_rack_and_pinion_r
      - servo_scoop_a
      - servo_scoop_b
      - dc_scoop
      - servo_sampler_lift_l
      - servo_sampler_lift_r
      - dc_auger
      - servo_auger_lift
    gpios:
      - spectrometry_laser
      - fluoro_led
      - science_limit_switch
    command_interfaces:
      spectrometry_laser:
        interfaces:
          - status_request
      fluoro_led:
        interfaces:
          - status_request
      science_limit_switch:
        interfaces:
          - status_request
      dc_scoop:
        interfaces:
          - status_request
          - maintenance_request
          - maintenance_frame_high
          - maintenance_frame_low
          - maintenance_data_count
      dc_auger:
        interfaces:
          - status_request
          - maintenance_request
          - maintenance_frame_high
          - maintenance_frame_low
          - maintenance_data_count
    state_interfaces:
      stepper_motor_a:
        interfaces:
          - status
      stepper_motor_b:
        interfaces:
          - status
      servo_rack_and_pinion_l:
        interfaces:
          - status
      servo_rack_and_pinion_r:
        interfaces:
          - status
      servo_scoop_a:
        interfaces:
          - status
      servo_scoop_b:
        interfaces:
          - status
      dc_scoop:
        interfaces:
          - status
      servo_sampler_lift_l:
        interfaces:
          - status
      servo_sampler_lift_r:
        interfaces:
          - status
      dc_auger:
        interfaces:
          - status
      servo_auger_lift:
        interfaces:
          - status
      fluoro_led:
        interfaces:
          - status
      science_limit_switch:
        interfaces:
          - status
    publish_rate: 10.0
