/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:             
      type: position_controllers/JointGroupPositionController

    joint_group_velocity_controller:              
      type: velocity_controllers/JointGroupVelocityController

    science_controller:
      type: science_controllers/ScienceManual

    # CCD Controller (CAN-based)
    ccd_controller:
      type: science_controllers/CCDSnapshotController

    conveyor_belt_cls_controller:
      type: science_controllers/ConveyorBeltCLSController

    # Laser GPIO Controller (CAN-based)
    laser_gpio_controller:
      type: gpio_controllers/GpioCommandController

    photodiode_gpio_controller:
      type: gpio_controllers/GpioCommandController

    motor_status_broadcaster:
      type: general_controllers/MotorStatusBroadcaster

    fluoro_led_gpio_controller:
      type: gpio_controllers/GpioCommandController

    motor_status_controller:
      type: general_controllers/MotorStatusController

    conveyor_belt_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

/**/joint_group_position_controller:
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_scoops_lift_f
      - servo_scoops_lift_b
      - servo_sampler_lift_f
      - servo_sampler_lift_b
      - servo_conveyor_belt
      - servo_scoop_f
      - servo_scoop_b
      - servo_auger_lift
      - dc_scoop
      - dc_auger
    interface_name: position

/**/joint_group_velocity_controller:
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_scoops_lift_f
      - servo_scoops_lift_b
      - servo_sampler_lift_f
      - servo_sampler_lift_b
      - servo_conveyor_belt
      - servo_scoop_f
      - servo_scoop_b
      - servo_auger_lift
      - dc_scoop
      - dc_auger
    interface_name: velocity

/**/science_controller:
  ros__parameters:
    # Joint names
    # Pumps
    pump_right: "stepper_motor_a"
    pump_left: "stepper_motor_b"
    
    # Scoops Lift
    scoops_lift_f: "servo_scoops_lift_f"
    scoops_lift_b: "servo_scoops_lift_b"

    # Sampler
    sampler_lift_f: "servo_sampler_lift_f"
    sampler_lift_b: "servo_sampler_lift_b"

    # Conveyor Belt
    conveyor_belt: "servo_conveyor_belt"
    
    # Scoops
    scoop_servos: ["servo_scoop_f", "servo_scoop_b"]
    scoop_spinner: "dc_scoop"

    auger_spinner: "dc_auger"
    auger_lift: "servo_auger_lift"
    interface_name: position 
    command_interfaces: [position, velocity]
    state_interfaces: [position, velocity]

    # Joint limits
    velocity_limits_pumps: [20.0, 0.0, 0.6, 0.0]
    velocity_limits_scoops_lift: [200.0, 0.1, 0.0, 0.3]
    position_range_scoop_servo_f: [20.0, 120.0]
    position_range_scoop_servo_b: [0.0, 110.0]
    velocity_limits_scoop_spinner: [30.0, 0.0, 0.6, 0.0]
    velocity_limits_sampler_lift: [200.0, 0.0, 0.0, 0.6]
    velocity_limits_auger: [2.5, 0.0, 0.0, 0.6]
    position_range_auger_lift: [5.0, 360.0]
    velocity_limits_conveyor_belt: [200.0, 0.0, 0.0, 0.6]

/**/ccd_controller:
  ros__parameters:
    ccd_name: "spectrometry_ccd"
    command_interfaces: ["capture_byte"]
    state_interfaces:
      - is_connected
      - command_success
      - acquisition_in_progress
      - data_ready
      - frames_received
      - last_frame_id
      
    snapshot_service_name: "~/request_snapshot"
    status_publish_topic: "~/status"
    snapshot_publish_topic: "/raman/raw_spectrum"

    publish_rate: 10.0
    acquisition_timeout_sec: 5.0
    expected_total_frames: 609

/**/conveyor_belt_cls_controller:
  ros__parameters:
    conveyor_belt_joint: "servo_conveyor_belt"
    rotary_encoder_joint: "conveyor_belt_encoder"
    magnetic_limit_switch_name: "science_magnetic_limit_switch"
    reference_topic: "~/reference"
    operating_velocity: 1.0
    encoder_state_request_rate: 20.0
    position_tolerance: 0.02
    kP: 1.0
    kI: 0.0
    kD: 0.0

# Laser GPIO Controller Configuration
/**/laser_gpio_controller:
  ros__parameters:
    gpios:
      - spectrometry_laser
    command_interfaces:
      spectrometry_laser:
        interfaces:
          - laser_command
    state_interfaces:
      spectrometry_laser:
        interfaces:
          - laser_state
          - is_connected

# Photodiode Controller Configuration
photodiode_gpio_controller:
  ros__parameters:
    gpios:
      - photodiode
    command_interfaces:
      photodiode:
        interfaces:
          - request_measurement_rate
    state_interfaces:
      photodiode:
        interfaces:
          - wavelength_intensity
          - command_success
          - is_connected
          - status

fluoro_led_gpio_controller:
  ros__parameters:
    gpios:
      - fluoro_led
    command_interfaces:
      fluoro_led:
        interfaces:
          - toggle
    state_interfaces:
      fluoro_led:
        interfaces:
          - is_connected
          - status

/**/conveyor_belt_velocity_controller:
  ros__parameters:
    joints:
      - servo_conveyor_belt
    interface_name: velocity

# Default command interfaces: 
# - status_request
# - maintenance_request
# - maintenance_frame_high
# - maintenance_frame_low
# - maintenance_data_count

# Default state interfaces:
# - motor_temperature
# - torque_current
# - status
/**/motor_status_controller:
  ros__parameters:
    joints:
      - stepper_motor_a
      - stepper_motor_b
      - servo_scoops_lift_f
      - servo_scoops_lift_b
      - servo_sampler_lift_f
      - servo_sampler_lift_b
      - servo_conveyor_belt
      - servo_scoop_f
      - servo_scoop_b
      - servo_auger_lift
      - dc_scoop
      - dc_auger
    gpios:
      - spectrometry_laser
      - photodiode
      - fluoro_led
      - science_limit_switch
      - science_magnetic_limit_switch
    command_interfaces:
      spectrometry_laser:
        interfaces:
          - status_request
      photodiode:
        interfaces:
          - status_request
      fluoro_led:
        interfaces:
          - status_request
      science_limit_switch:
        interfaces:
          - status_request
      science_magnetic_limit_switch:
        interfaces:
          - status_request
      dc_scoop:
        interfaces:
          - status_request
          # - maintenance_request
          # - maintenance_frame_high
          # - maintenance_frame_low
          # - maintenance_data_count
      dc_auger:
        interfaces:
          - status_request
          # - maintenance_request
          # - maintenance_frame_high
          # - maintenance_frame_low
          # - maintenance_data_count
    state_interfaces:
      stepper_motor_a:
        interfaces:
          - status
      stepper_motor_b:
        interfaces:
          - status
      servo_scoops_lift_f:
        interfaces:
          - status
      servo_scoops_lift_b:
        interfaces:
          - status
      servo_conveyor_belt:
        interfaces:
          - status
      servo_scoop_f:
        interfaces:
          - status
      servo_scoop_b:
        interfaces:
          - status
      dc_scoop:
        interfaces:
          - status
      servo_sampler_lift_f:
        interfaces:
          - status
      servo_sampler_lift_b:
        interfaces:
          - status
      dc_auger:
        interfaces:
          - status
      servo_auger_lift:
        interfaces:
          - status
      photodiode:
        interfaces:
          - status
      fluoro_led:
        interfaces:
          - status
      science_limit_switch:
        interfaces:
          - status
      science_magnetic_limit_switch:
        interfaces:
          - status
      spectrometry_laser:
        interfaces:
          - status
    publish_rate: 10.0
