motor_status_controller:
  joints: {
    type: string_array,
    default_value: [],
    description: "Names of the joints to monitor for motor telemetry."
  }
  gpios: {
    type: string_array,
    default_value: [],
    description: "Names of the GPIOs to monitor for status telemetry."
  }
  command_interfaces: 
    __map_joints:
      interfaces: {
        type: string_array,
        default_value: ["status_request", "maintenance_request", "maintenance_frame_high", "maintenance_frame_low", "maintenance_data_count"],
        description: "Command interface names to read from each joint. Leave empty if no command interfaces are needed.",
        validation: {
          unique<>: null
        }
      }
    __map_gpios:
      interfaces: {
        type: string_array,
        default_value: ["status_request"],
        description: "Command interface names to read from each GPIO. Leave empty if no command interfaces are needed.",
        validation: {
          unique<>: null
        }
      }
  state_interfaces: 
    __map_joints:
      interfaces: {
        type: string_array,
        default_value: ["motor_temperature", "torque_current", "status"],
        description: "State interface names to read from each joint.",
        validation: {
          unique<>: null
        }
      }
    __map_gpios:
      interfaces: {
        type: string_array,
        default_value: ["status"],
        description: "State interface names to read from each GPIO.",
        validation: {
          unique<>: null
        }
      }
  publish_rate: {
    type: double,
    default_value: 10.0,
    description: "Rate (Hz) at which to publish diagnostics. Set to 0 to publish every update cycle.",
    validation: {
      gt_eq<>: [0.0]
    }
  }
